### ISSUE TITLE
WES Host should be configurable in the swagger template json

### ISSUE THREAD

**Issue by lepsalex** [icgc-argo/workflow-docs#9]
`workflow-docs/WES-swagger-template.json`

- host needs to be configurable

**Comment by rosibaj** [comment]
@lepsalex @Buwujiu Is this deployed yet?

**Comment by Buwujiu** [comment]
@rosibaj yes it's deployed! But you don't really need to test this, it's a devop ticket.

**Comment by rosibaj** [comment]
@Buwujiu yup, but verifying it is deployed as someone was asking for it!!

**Comment by lepsalex** [comment]
is there a release? we need to deploy this into the rdpc cluster then
